### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by mrocklin** [ian-r-rose/jupyterlab-bokeh-server#9]
@ian-r-rose , how would you like to handle this?

**Comment by mrocklin** [comment]
I'm feeling a little bit of time pressure on this by the way.  We ended up forking this off into https://github.com/jacobtomlinson/jupyterlab-nvdashboard (checkout the gif in the readme) and would like to include that in the RAPIDS Docker image, but need to make sure that things are squared away with a license before we do so.

I have a preference for some permissive license (BSD, MIT, Apache 2.0).  I suspect that you do as well.  I don't have a preference between them.

**Comment by ian-r-rose** [comment]
Whops, good catch. I usually go with BSD 3-clause for things that are in the broader Jupyter ecosystem, so I think we should do that here.

For personal projects, I actually rather like GPL :)

**Comment by mrocklin** [comment]
OK.  Author name?  Jupyter Development Team?

**Comment by ian-r-rose** [comment]
I'd go with the two of us

**Comment by mrocklin** [comment]
See https://github.com/ian-r-rose/jupyterlab-bokeh-server/pull/10
